"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { saveDraft } from "@/lib/server/cms-actions";

export default function ProjectEditor({ media = [] }: { media?: { id: string; alt: string; pathname: string }[] }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(form: FormData) { setBusy(true); setError(""); try { const localized = (locale: "id" | "en") => ({ title: String(form.get(`${locale}Title`)), category: String(form.get(`${locale}Category`)), summary: String(form.get(`${locale}Summary`)), role: String(form.get(`${locale}Role`)), body: [{ type: "paragraph" as const, text: String(form.get(`${locale}Body`)) }], seoTitle: String(form.get(`${locale}SeoTitle`)), seoDescription: String(form.get(`${locale}SeoDescription`)) }); const result = await saveDraft("PROJECT", null, String(form.get("slug")), { slug: String(form.get("slug")), content: { id: localized("id"), en: localized("en") }, year: String(form.get("year")), stack: String(form.get("stack")).split(",").map((value) => value.trim()).filter(Boolean), featured: form.get("featured") === "on", sortOrder: Number(form.get("sortOrder") || 0), heroMediaId: String(form.get("heroMediaId") || "") || null, galleryMediaIds: [], liveUrl: String(form.get("liveUrl") || "") || null, repositoryUrl: null }); router.push(`/admin/projects/${result.documentId}`); } catch { setError("Draft gagal disimpan. Pastikan konten Indonesia dan English sudah lengkap."); } finally { setBusy(false); } }
  return <form className="admin-callout" action={submit}><label>Slug<input name="slug" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" /></label><label>Tahun<input name="year" /></label><label>Stack<input name="stack" placeholder="Next.js, TypeScript" /></label><label>Live URL<input name="liveUrl" type="url" /></label><label>Hero media<select name="heroMediaId"><option value="">Fallback grafis internal</option>{media.map((asset) => <option key={asset.id} value={asset.id}>{asset.alt} · {asset.pathname}</option>)}</select></label>{(["id", "en"] as const).map((locale) => <fieldset key={locale}><legend>{locale === "id" ? "Bahasa Indonesia" : "English"}</legend><label>Judul<input name={`${locale}Title`} required /></label><label>Kategori<input name={`${locale}Category`} required /></label><label>Peran<input name={`${locale}Role`} required /></label><label>Ringkasan<textarea name={`${locale}Summary`} required /></label><label>Cerita<textarea name={`${locale}Body`} required /></label><label>SEO title<input name={`${locale}SeoTitle`} required /></label><label>SEO description<textarea name={`${locale}SeoDescription`} required /></label></fieldset>)}<label><input type="checkbox" name="featured" /> Featured</label><button className="button button-light" disabled={busy}>{busy ? "Menyimpan…" : "Simpan draft"}</button><p aria-live="polite">{error}</p></form>;
}
