"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { saveDraft } from "@/lib/server/cms-actions";

export default function ProjectEditor({ media = [] }: { media?: { id: string; alt: string; pathname: string }[] }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(form: FormData) { setBusy(true); setError(""); try { const result = await saveDraft("PROJECT", null, String(form.get("slug")), { slug: String(form.get("slug")), title: String(form.get("title")), category: String(form.get("category")), year: String(form.get("year")), summary: String(form.get("summary")), role: String(form.get("role")), stack: String(form.get("stack")).split(",").map((value) => value.trim()).filter(Boolean), featured: form.get("featured") === "on", sortOrder: Number(form.get("sortOrder") || 0), heroMediaId: String(form.get("heroMediaId") || "") || null, galleryMediaIds: [], body: [{ type: "paragraph", text: String(form.get("body")) }], liveUrl: null, repositoryUrl: null, seoTitle: String(form.get("title")), seoDescription: String(form.get("summary")) }); router.push(`/admin/projects/${result.documentId}`); } catch { setError("Draft gagal disimpan. Periksa input dan konfigurasi CMS."); } finally { setBusy(false); } }
  return <form className="admin-callout" action={submit}><label>Slug<input name="slug" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" /></label><label>Judul<input name="title" required /></label><label>Kategori<input name="category" /></label><label>Tahun<input name="year" /></label><label>Peran<input name="role" /></label><label>Stack<input name="stack" placeholder="Next.js, TypeScript" /></label><label>Hero media<select name="heroMediaId"><option value="">Fallback grafis internal</option>{media.map((asset) => <option key={asset.id} value={asset.id}>{asset.alt} · {asset.pathname}</option>)}</select></label><label>Ringkasan<textarea name="summary" required /></label><label>Cerita<textarea name="body" required /></label><label><input type="checkbox" name="featured" /> Featured</label><button className="button button-light" disabled={busy}>{busy ? "Menyimpan…" : "Simpan draft"}</button><p aria-live="polite">{error}</p></form>;
}
